[project]
name = "santiago-aguirre"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sanjiacoaguirregonzalez@gmail.com", email = "sanjiacoaguirre@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
santiago-aguirre = "santiago_aguirre:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
